services:
  db:
    container_name: nest-url-shortner-db
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=nest_url_shortner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ps_secret
    ports:
      - '5432:5432'
    networks:
      - dev

networks:
  dev:
    driver: bridge
    name: 'nest-url-shortner'
